### ISSUE TITLE
SeekToFirst SeekToLast does not work

### ISSUE THREAD

**Issue by CodingCrush** [bobotu/myk#1]
Hi, @bobotu 
It seems that `SeekToFirst` `SeekToLast` does not work in Iterator.
A key should be seeked before iterating over the surf tree manually. Otherwise, the Key() method won't outputs the correct data.

----------------
```
func Test_Surf_Iterate(t *testing.T) {
	builder := NewBuilder(2, 0, 1)
	var keys [][]byte
	var values [][]byte
	for x := 1; x <= 10; x++ {
		for y := 1; y < 1<<8; y++ {
			for z := 1; z < 1<<8; z++ {
				keys = append(keys, []byte(fmt.Sprintf("192.%d.%d.%d", x, y, z)))
				values = append(values, u16ToBytes(uint16(z)))
			}
		}
	}

	sort.Slice(keys, func(i, j int) bool {
		return bytes.Compare(keys[i], keys[j]) < 0
	})

	fst := builder.Build(keys, values, 0)
	itr := fst.NewIterator()
	// normal cases:
	itr.Seek([]byte("192.1.1.1"))
	fmt.Println(string(itr.Key()))
	itr.Next()
	fmt.Println(string(itr.Key()))

	// abnormal cases:
	itr.SeekToFirst()
	fmt.Println(string(itr.Key()))
	itr.Next()
	fmt.Println(string(itr.Key()))
	itr.SeekToLast()
	fmt.Println(string(itr.Key()))
	itr.Prev()
	fmt.Println(string(itr.Key()))
}
```

--------------------
```
=== RUN   Test_Surf_Iterate
// seek the first key manually, it works well
192.1.1.1
192.1.1.10

// SeekToFirst losts the prefix
1.1.1
1.1.1�1.10

// SeekToLast
9.99.99
9.99.99.108

```

**Comment by bobotu** [comment]
Sorry for the late reply. The surf package in this repo is outdated, I have just updated it to include some fixes which made several months ago when using it in another project. Could you try the latest master to check if this bug still exists?

**Comment by CodingCrush** [comment]
> Sorry for the late reply. The surf package in this repo is outdated, I have just updated it to include some fixes which made several months ago when using it in another project. Could you try the latest master to check if this bug still exists?


Thank you for your selfless work, These two methods are fixed now. 
But I'm wondering why another bug still reproduced, or do I use it in the wrong way?

```
func Test_Surf(t *testing.T) {
	host := []string{
		"nj-1",
		"nj-2",
		"nj-3",
		"sh-4",
		"sh-5",
		"sh-6000",
		"bj-7",
		"bj-8",
		"bj-9"}

	builder := NewBuilder(1, 0, 1)
	var keys [][]byte
	var values [][]byte
	for _, key := range host {
		keys = append(keys, []byte(key))
		values = append(values, []byte{1})
	}
	sort.Slice(keys, func(i, j int) bool {
		return bytes.Compare(keys[i], keys[j]) < 0
	})
	tree := builder.Build(keys, values, 8)
	itr := tree.NewIterator()
	itr.SeekToFirst()
	for itr.Valid() {
                 // sh-6000 is stored as sh-6
		fmt.Println(string(itr.Key()))
		itr.Next()
	}
        // different suffix length and hash length returns differents value at here
	fmt.Println(tree.Get([]byte("sh-59"))) // [1] true
	fmt.Println(tree.Get([]byte("sh-61"))) // [1] true
	fmt.Println(tree.Get([]byte("sh-69"))) // [1] true
	fmt.Println(tree.Get([]byte("sh-71"))) // [] false
}
```

**Comment by bobotu** [comment]
The SuRF will discard the unique suffix for a key.
* `Iterator.Next` can only return the prefix for a key (sh-6000 -> sh-6 in your case).
* `Get` have some false positive rate (sh-59 returns true but this key actually not in SuRF)
* The false positive rate is controlled by `suffix length` and `hash length`.
	* The more bits allocated for `suffix` or `hash` the less false positive you will meet. The paper of SuRF contains more detailed charts for this feature.

SuRF is just used as a probability index tree.
* You store all of your key-value pairs in a sequence file.
* SuRF contains the `key -> file offset` mapping of each value.
* Now you can do a quick search for any key and may get an offset.
* Because the SuRF has false positive you must load the data from the file and check whether the key is actually matched.

Examples above just a simple use case.

BTW, it is possible to directly store the unique suffix into the SuRF, but I don't have time to implement it in the near future.

**Comment by CodingCrush** [comment]
> The SuRF will discard the unique suffix for a key.
> 
> * `Iterator.Next` can only return the prefix for a key (sh-6000 -> sh-6 in your case).
> * `Get` have some false positive rate (sh-59 returns true but this key actually not in SuRF)
> * The false positive rate is controlled by `suffix length` and `hash length`.
>   
>   * The more bits allocated for `suffix` or `hash` the less false positive you will meet. The paper of SuRF contains more detailed charts for this feature.
> 
> SuRF is just used as a probability index tree.
> 
> * You store all of your key-value pairs in a sequence file.
> * SuRF contains the `key -> file offset` mapping of each value.
> * Now you can do a quick search for any key and may get an offset.
> * Because the SuRF has false positive you must load the data from the file and check whether the key is actually matched.
> 
> Examples above just a simple use case.
> 
> BTW, it is possible to directly store the unique suffix into the SuRF, but I don't have time to implement it in the near future.

Thank you for your informative answer.
I misunderstood the meaning of FPR in the paper. I thought the mixed suffix was used to decrease the nodes number before, and the full suffix will be stored in a byte slice for better performance
